name: Scheduled MongoDB Ingestion

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  # Allows manual triggers from GitHub UI
  workflow_dispatch:

jobs:
  ingest-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pymongo dnspython faker

      - name: Run MongoDB Ingestion Script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python ingest.py
